
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "external/pico-extras/CMakeLists.txt:12 (project)"
    message: |
      The target system is: PICO -  - cortex-m0plus
      The host system is: Windows - 10.0.19045 - 
...
